[project]
name = "celestrak-scrapping"
version = "3.0.0"
description = "Celestrak scrapper"
requires-python = ">=3.12"
dependencies = [
    "dynaconf>=3.2.13",
    "psycopg[binary]>=3.3.4",
    "requests>=2.34.2",
    "shapely>=2.1.2",
    "skyfield>=1.54",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "flake8>=7.3.0",
    "pytest>=9.0.3",
    "ty>=0.0.41",
]

[tool.pytest.ini_options]
pythonpath = [
    "src"
]
